Bump diesel from 2.3.8 to 2.3.9 in /cli in the rust-deps group across 1 directory (#520)
Bumps the rust-deps group with 1 update in the /server directory:
[diesel](https://github.com/diesel-rs/diesel).

Updates `diesel` from 2.3.8 to 2.3.9
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/diesel-rs/diesel/blob/main/CHANGELOG.md">diesel's
changelog</a>.</em></p>
<blockquote>
<h2>[2.3.9] 2026-04-30</h2>
<ul>
<li>Removed a <code>dbg!</code> statement from the Mysql backend that
caused unwanted output</li>
<li>Fix a regression in <code>#[derive(AsChangeset)]</code> introduced
in 2.3.8 where structs with a type or const generic parameter referenced
in a field type failed to compile with <code>error[E0425]: cannot find
type 'T' in this scope</code>. The diagnostic helper functions added to
improve <code>AsChangeset</code> error messages now forward all generic
parameters of the input struct, not only lifetimes.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/diesel-rs/diesel/commit/2e7eb3567574f6d8660e97ab83abac1b71631e63"><code>2e7eb35</code></a>
Also bump derives version</li>
<li><a
href="https://github.com/diesel-rs/diesel/commit/b3a16a34822b94596e260cdd9aa9fbbe05166e91"><code>b3a16a3</code></a>
Merge pull request <a
href="https://redirect.github.com/diesel-rs/diesel/issues/5046">#5046</a>
from apastrana6/ap/fix-derive-as-changeset</li>
<li><a
href="https://github.com/diesel-rs/diesel/commit/9f0a6c16bd4634a1387161449a83d152061d1879"><code>9f0a6c1</code></a>
Prepare a 2.3.9 release</li>
<li><a
href="https://github.com/diesel-rs/diesel/commit/adcc8965b869789e5666a2f3d929e9bf8381f32c"><code>adcc896</code></a>
Enable some clippy lints to prevent having dbg in a release again</li>
<li><a
href="https://github.com/diesel-rs/diesel/commit/66760dff30bee97f73780e71d3e4d1816e506489"><code>66760df</code></a>
Remove MySQL time serializer debug output</li>
<li>See full diff in <a
href="https://github.com/diesel-rs/diesel/compare/v2.3.8...v2.3.9">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=diesel&package-manager=cargo&previous-version=2.3.8&new-version=2.3.9)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>